### ISSUE TITLE
parse error of ! on asir built by --enable-fep

### ISSUE THREAD

**Issue by mitsushi-fujimoto** [openxm-org/OpenXM#1]
asir (editline version) cannot parse inputs with '!'.

$ asir
This is Risa/Asir, full GMP Version 20220911 (Kobe Distribution).
Copyright (C) 1994-2000, all rights reserved, FUJITSU LABORATORIES LIMITED.
Copyright 2000-2021, Risa/Asir committers, http://www.openxm.org/.
GC 7.6.12 copyright 1988-2018, H-J. Boehm, A. J. Demers, Xerox, SGI, HP, I. Maidanski.
[0] 0!;
0
[1] 1!;
1
[2] 2!;
2
[3] 3!;
3
[4] 10!;
10
[5] 10!/2;
/2;: Event not found
[5]

**Comment by nobuki-takayama** [comment]
Add space after !,  e.g.,  3! ;  (comment by Ohara).

2022-09-12 13:36 に Mitsushi Fujimoto さんは書きました:

**Comment by mitsushi-fujimoto** [comment]
This issue was fixed by Ohara.
[asir2018/parse/glob.c](https://github.com/openxm-org/OpenXM_contrib2/commit/0cc285c6bede7375c8b9475c37cc907e1df62380)
