### ISSUE TITLE
finer type

### ISSUE THREAD

**Issue by fchapoton** [openxm-org/OpenXM#6]
the command `type` currently returns only a very rough information (number or matrix or list, etc)

is there another way to have finer information ? for example, can one distinguish between integers and real and complex numbers ? Would it make sense to change the behaviour of `type` to allow that ?

**Comment by nobuki-takayama** [comment]
Use ntype [http://www.math.sci.kobe-u.ac.jp/OpenXM/Current/doc/asir2000/html-en/man/man_35.html#ntype]

**Comment by fchapoton** [comment]
thanks
